-- Expand tournaments table to support comprehensive tournament configuration
ALTER TABLE public.tournaments 
ADD COLUMN IF NOT EXISTS tournament_date timestamp with time zone,
ADD COLUMN IF NOT EXISTS late_registration_levels integer DEFAULT 4,
ADD COLUMN IF NOT EXISTS late_registration_minutes integer DEFAULT 60,
ADD COLUMN IF NOT EXISTS rebuy_allowed boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS rebuy_levels integer DEFAULT 3,
ADD COLUMN IF NOT EXISTS rebuy_stack integer DEFAULT 10000,
ADD COLUMN IF NOT EXISTS addon_allowed boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS addon_levels integer DEFAULT 3,
ADD COLUMN IF NOT EXISTS addon_stack integer DEFAULT 5000,
ADD COLUMN IF NOT EXISTS addon_cost integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS starting_chips integer DEFAULT 10000,
ADD COLUMN IF NOT EXISTS chip_colors jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS level_duration_type text DEFAULT 'fixed',
ADD COLUMN IF NOT EXISTS custom_level_durations jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS break_frequency integer DEFAULT 4,
ADD COLUMN IF NOT EXISTS break_duration integer DEFAULT 15,
ADD COLUMN IF NOT EXISTS first_break_after integer DEFAULT 4,
ADD COLUMN IF NOT EXISTS antes_start_level integer DEFAULT 5,
ADD COLUMN IF NOT EXISTS payout_percentage integer DEFAULT 100,
ADD COLUMN IF NOT EXISTS min_players integer DEFAULT 2,
ADD COLUMN IF NOT EXISTS max_players integer DEFAULT 100,
ADD COLUMN IF NOT EXISTS registration_fee integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS dealer_tip_percentage integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS satellite_target text,
ADD COLUMN IF NOT EXISTS qualifier_seats integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS description text,
ADD COLUMN IF NOT EXISTS rules text,
ADD COLUMN IF NOT EXISTS blind_structure_type text DEFAULT 'standard',
ADD COLUMN IF NOT EXISTS starting_blinds_sb integer DEFAULT 25,
ADD COLUMN IF NOT EXISTS starting_blinds_bb integer DEFAULT 50,
ADD COLUMN IF NOT EXISTS blind_increase_type text DEFAULT 'standard',
ADD COLUMN IF NOT EXISTS custom_blind_schedule jsonb DEFAULT '[]'::jsonb;