// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohvboilegetblfwjipsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9odmJvaWxlZ2V0Ymxmd2ppcHNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDcyNTksImV4cCI6MjA2NjQyMzI1OX0.cK4KHKBh6a5Kyyx2O0iLMRkcWA8_SdeKFxhwMjfFNdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);